build:
  version: "3.3"

cards:
  message: "Welcome to cards related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@pblgllgs.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934