spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - "application_qa.yaml"
      - "application_prod.yaml"
  profiles:
    active: prod
server:
  port: 8080

build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@pblgllgs.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345