build:
  version: "3.2"

loans:
  message: "Welcome to loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer prod"
    email: "amaal@pblgllgs.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934