spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: prod
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"