build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@pblgllgs.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345