spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway server application service"
    version: "0.0.8"

logging:
  level:
    com:
      pblgllgs:
        gatewayserver: DEBUG
